### ISSUE TITLE
Lacks 1 piece in Tetris

### ISSUE THREAD

**Issue by johanchouquet** [web-dave/ng-tetris#8]
Great game in Angular Dave!

I was playing quite good, and it seems to me that there was missing one piece of Tetris:
the podium one, like [this one here](https://www.123rf.com/photo_936775_classic-tetris-game-two-pieces-fit-together.html).

**Comment by web-dave** [comment]
Happy you like it.
I implemented all available pieces.

https://github.com/web-dave/ng-tetris/blob/c798df098c0eaf94a1a4f875c50c62df1b04f00f/src/app/pieces.service.ts#L7
